### ISSUE TITLE
下载的视频提示升级客户端

### ISSUE THREAD

**Issue by Dave-pan** [here200/CCTallk-Video-Download#1]
我购买的视频不能网页观看，请问这种情况是无法下载吗？
![image](https://user-images.githubusercontent.com/61072063/154832948-2ea95bb1-81f0-4074-9384-e6ae0244dd0a.png)

![image](https://user-images.githubusercontent.com/61072063/154832855-f10874a5-c170-474c-b0bc-bff6d903319a.png)

**Comment by here200** [comment]
很抱歉在写软件时没有考虑到这种情况。因为我之前并没有遇到过这种情况。
详细信息可以查看链接 https://www.cctalk.com/faq/100175

**Comment by Dave-pan** [comment]
好的，谢谢😂
