### ISSUE TITLE
代码中的视频下载被注释掉了

### ISSUE THREAD

**Issue by Satoing** [here200/CCTallk-Video-Download#3]
非常感谢作者，我也不用自己去写爬虫了。不过代码中调用`download_movie()`被注释掉了，加上就行了（函数参数也改一下）。
![image](https://user-images.githubusercontent.com/68995451/187015559-9c030150-98ae-4ac6-ae15-bef280dc754e.png)
![image](https://user-images.githubusercontent.com/68995451/187015492-9cf53ae5-9c71-4d3f-a7f8-b24b5b3645e1.png)

**唔，下完才发现另一个问题，下载的视频是没有序号的，最后还要手动编号。不如直接在程序中加上：**
![image](https://user-images.githubusercontent.com/68995451/187015956-d4c03c45-27c7-49e4-81e7-adc7b74b4ef6.png)
> 另外，看起来作者和我要下载的应该是同一个视频呢哈哈

**Comment by here200** [comment]
download_movie() 注释掉，这样默认才不会直接下载视频。

把 打印视频列表信息 和 下载视频 分开，
	这样才好根据打印的信息选择自己想要下载的视频，
	毕竟不是所有人都想要下载所有的视频，可能只是想下载部分视频。

视频序号看情况了，有些老师它会给自己的视频设置编号，有些不会，因人而异。

感谢你的使用。
